// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3GUeo30C4HhWoP8daH7bfL8KheQgjAWM',
    appId: '1:247519758782:web:f0bf6ce64ebccebe5c91ef',
    messagingSenderId: '247519758782',
    projectId: 'wheatmap-2d95d',
    authDomain: 'wheatmap-2d95d.firebaseapp.com',
    storageBucket: 'wheatmap-2d95d.appspot.com',
    measurementId: 'G-FTHTC1DZET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbogtVDSrJ1fLBvyv5PTloQ65yT415Jgw',
    appId: '1:247519758782:android:63e099c7978869925c91ef',
    messagingSenderId: '247519758782',
    projectId: 'wheatmap-2d95d',
    storageBucket: 'wheatmap-2d95d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXE5srKI8C8NuhW5hTbxhK3pJvxM_-i6w',
    appId: '1:247519758782:ios:a09917e5483c2bfe5c91ef',
    messagingSenderId: '247519758782',
    projectId: 'wheatmap-2d95d',
    storageBucket: 'wheatmap-2d95d.appspot.com',
    androidClientId: '247519758782-emhnuk31liglpmpni2f7mdo894mvh6cc.apps.googleusercontent.com',
    iosClientId: '247519758782-jrp7nsp2gnutbu7ulqkjkklu9pbjal0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheatmap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXE5srKI8C8NuhW5hTbxhK3pJvxM_-i6w',
    appId: '1:247519758782:ios:a09917e5483c2bfe5c91ef',
    messagingSenderId: '247519758782',
    projectId: 'wheatmap-2d95d',
    storageBucket: 'wheatmap-2d95d.appspot.com',
    androidClientId: '247519758782-emhnuk31liglpmpni2f7mdo894mvh6cc.apps.googleusercontent.com',
    iosClientId: '247519758782-jrp7nsp2gnutbu7ulqkjkklu9pbjal0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.wheatmap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GUeo30C4HhWoP8daH7bfL8KheQgjAWM',
    appId: '1:247519758782:web:72d00ce2b242bc315c91ef',
    messagingSenderId: '247519758782',
    projectId: 'wheatmap-2d95d',
    authDomain: 'wheatmap-2d95d.firebaseapp.com',
    storageBucket: 'wheatmap-2d95d.appspot.com',
    measurementId: 'G-52C3PDL1MY',
  );

}